

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-module
  template:
    metadata:
      labels:
        app: bank-module
    spec:
      containers:
        - name: bank-module
          image: shmuelhalbfinger/practiceatmbankapp:bank-module
          ports:
            - containerPort: 8082
              name: bank-module
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: bank-module
spec:
  selector:
    app: bank-module
  ports:
    - port: 80
      targetPort: 8082
      nodePort: 31234
  type: NodePort

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bank-module-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host:
      http:
        paths:
          - backend:
              serviceName: bank-module
              servicePort: 31234
            path: /bank